version: "3.9"

services:
  building:
    image: sban_building
    volumes:
      - building_data:/data
    environment:
      SBAN_AREA: $SBAN_AREA
      SBAN_BACKEND: mqtt.sban.org
      SBAN_FAKE_LOCATION_CITY: $SBAN_FAKE_LOCATION_CITY
      SBAN_FAKE_LOCATION_COUNTRY: $SBAN_FAKE_LOCATION_COUNTRY
      SBAN_BUILDING: $SBAN_BUILDING
    ports:
      - "21880:1880"
      - "1883"
    networks:
      - backend-net
      - building-net

  actuator:
    image: sban_actuator
    volumes:
      - actuator_data:/data
    ports:
      - "21881-22881:1880"
    environment:
      # ROOM_ID: "{{.Task.Slot}}"
      SBAN_BUILDING_HOST: building
    deploy:
      replicas: ${SBAN_ROOM_COUNT}
    networks:
      - building-net

  contiki-ng:
    image: sban_contiki-ng
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    ports:
      - "1883"
    volumes:
      - type: bind
        source: $CNG_PATH
        target: /home/user/contiki-ng
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    environment:
      DISPLAY: $DISPLAY
      SBAN_AREA: $SBAN_AREA
      SBAN_BUILDING: $SBAN_BUILDING
      SBAN_BUILDING_HOST: building
    networks:
      - building-net

networks:
  backend-net:
    name: sban_backend-net
    external: true
  building-net:

volumes:
  actuator_data:
    driver: local
  building_data:
    driver: local